// Fill out your copyright notice in the Description page of Project Settings.


#include "Utilities/BlueprintFunctionLibraries/BFL_HitResultHelpers.h"

#include "Utilities/LogCategories.h"

UMaterialInterface* UBFL_HitResultHelpers::GetHitMaterial(const FHitResult& InHitResult)
{
	UMaterialInterface* RetVal = nullptr;
	if (InHitResult.FaceIndex == -1)
	{
		UE_LOG(LogBlueprintFunctionLibrary, Error, TEXT("%s() failed because InHitResult.FaceIndex was -1. Make sure that the hit result passed in was generated by a trace with FCollisionQueryParams::bReturnFaceIndex set to true"), *FString(__FUNCTION__));
		return RetVal;
	}


	const UPrimitiveComponent* HitComponent = InHitResult.GetComponent();
	if (IsValid(HitComponent))
	{
		int32 sectionIndex;
		RetVal = HitComponent->GetMaterialFromCollisionFaceIndex(InHitResult.FaceIndex, sectionIndex);
	}


	return RetVal;
}
